services:
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery-worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      # rediss://:<access key>@<my server>.redis.cache.windows.net:6380/0
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

  celery-flower:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery-flower
    command: celery -A tasks flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
